version: '2.2'
services:
  nemo-nginx:
    image: nginx:latest
    container_name: nemo-nginx
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/opt/nemo-copilot/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/opt/nemo-copilot/nginx/conf.d:/etc/nginx/conf.d"
      - "/opt/nemo-copilot/frontend:/opt/nemo-copilot/frontend"
      - "/opt/nemo-copilot/frontend-boss:/opt/nemo-copilot/frontend-boss"
      - "/opt/nemo-copilot/nginx/logs:/var/log/nginx"
      - "/opt/nemo-copilot/nginx/www.xxx.pem:/etc/nginx/ssl/www.xxx.pem"
      - "/opt/nemo-copilot/nginx/www.xxx.key:/etc/nginx/ssl/www.xxx.key"
      - "/etc/localtime:/etc/localtime"
