- hosts: test
  become: yes
  become_method: sudo
  vars:
    image_tag: 0.1.0
    dashscope_api_key: ""
    dashscope_base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model_name: "deepseek-v4-flash"
    mcp_server_url: "http://{{ groups['test-nat'] | random }}:8770/api/agent/mcp"
    chart_server: "http://{{ groups['test-nat'] | random }}:9090"
  roles:
    - { role: toolbox, server_port: 8800}
