export const PERMISSIONS = {
  CHART_VIEW_DEMO: 'CHART_VIEW_DEMO',
  CHART_EDIT_DEMO: 'CHART_EDIT_DEMO',
  CHART_VIEW: 'CHART_VIEW',
  CHART_EDIT: 'CHART_EDIT',
  CHART_NEW: 'CHART_NEW',
  TASKS: 'TASKS',
} as const

export type TPermission = keyof typeof PERMISSIONS

export const SUBSCRIPTION_PERMISSION_GROUPS = {
  FREE: [
    PERMISSIONS.CHART_VIEW,
    PERMISSIONS.CHART_VIEW_DEMO,
    PERMISSIONS.CHART_EDIT_DEMO,
  ],
  STANDARD: [
    PERMISSIONS.CHART_VIEW,
    PERMISSIONS.CHART_EDIT,
    PERMISSIONS.CHART_NEW,
    PERMISSIONS.CHART_VIEW_DEMO,
    PERMISSIONS.CHART_EDIT_DEMO,
    PERMISSIONS.TASKS,
  ],
}
